apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.user.namespace }}
data:
  MONGO_URI: {{ .Values.config.mongoUri | quote }}
  PORT: {{ .Values.config.port | quote }}
