apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-user-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              until nc -z {{ .Values.mongo.serviceName }} {{ .Values.mongo.port }}; do
                echo "Waiting for Mongo..."
                sleep 2
              done
      containers:
        - name: user-service
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGO_URI
              value: mongodb://{{ .Values.mongo.serviceName }}:{{ .Values.mongo.port }}/userdb

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-user-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: user-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
