apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongo.serviceName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongo.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongo.serviceName }}
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          ports:
            - containerPort: {{ .Values.mongo.port }}
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 10
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongo.serviceName }}
spec:
  type: {{ .Values.mongo.serviceType | default "ClusterIP" }}
  selector:
    app: {{ .Values.mongo.serviceName }}
  ports:
    - port: {{ .Values.mongo.port }}
      targetPort: {{ .Values.mongo.port }}
