apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-service.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "user-service.name" . }}
  ports:
    - port: 3000
      targetPort: 3000
