replicaCount: 1

image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: mongo-service
  type: ClusterIP
  port: 27017

storage:
  size: 1Gi
  path: /mnt/data/mongo
  accessMode: ReadWriteOnce
