apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crud-ingress
  # namespace: microservice
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-cookie-path: "/=/"
    nginx.ingress.kubernetes.io/proxy-cookie-domain: "sss.mokchhedulislam.page.gd"
spec:
  ingressClassName: nginx
  rules:
  - host: sss.mokchhedulislam.page.gd
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: product-service
            port:
              number: 3001
      - path: /api/auth(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service
            port:
              number: 3000