apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.service.name}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{.Values.service.name}}
  template:
    metadata:
      labels:
        app: {{.Values.service.name}}
    spec:
      containers:
        - name: ecom-product
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: MONGO_URI
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ecom-config
                  key: PORT
