replicaCount: 1

image:
  repository: mokchhedul/userservice
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

mongo:
  image: mongo:6
  serviceName: mongo
  port: 27017
  serviceType: ClusterIP
