apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: product-mongo-pvc
  {% comment %} namespace: {{ .Values.product.namespace }} {% endcomment %}
spec:
  accessModes:
    - {{ .Values.db.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
