apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-mongo-pvc
  {% comment %} namespace: {{ .Values.cart.namespace }} {% endcomment %}
spec:
  accessModes:
    - {{ .Values.db.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
