apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  MONGO_URI: "mongodb://{{ .Values.db.service.name }}:{{ .Values.db.service.port }}/{{ .Values.db.service.dbname }}"
  PORT: "{{ .Values.cart.service.port }}"
