apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cart-mongo-pvc
spec:
  accessModes:
    - {{ .Values.db.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
