apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: user
spec:
  selector:
    app: {{ .Values.service.selector }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
